LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS) 

LOCAL_MODULE := PixelLauncher 
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := PixelLauncher.apk 
LOCAL_CERTIFICATE := platform 
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true 
LOCAL_OVERRIDES_PACKAGES := Launcher2
LOCAL_MODULE_SUFFIX :=$(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS) 
LOCAL_MODULE := WallpaperPickerGoogle 
LOCAL_MODULE_TAGS := optional 
LOCAL_SRC_FILES := WallpaperPickerGoogle.apk 
LOCAL_CERTIFICATE := platform 
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
